token:
  expiration_time: 950108 #300000 # 5ë¶„
  secret: user_token_hsss

gateway:
  ip: 192.168.61.252

ip:
  eureka: http://192.168.61.252:8761/eureka
  hostname: 192.168.61.252
  gateway: 192.168.61.252



